security:
    encoders:
        Blogger\BlogBundle\Entity\User:
            id: blogger.blog.sha256salted_encoder

    role_hierarchy:
        ROLE_USER:       ROLE_USER
        ROLE_ADMIN: [ROLE_ADMIN, ROLE_USER]

    providers:
        administrators:
            entity: { class: BloggerBlogBundle:User }

    firewalls:
        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login:
                check_path: login_check
                login_path: login
            logout:
                path:   /logout
                target: /
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
