BloggerAdminBundle_homepage:
    pattern:  /
    defaults: { _controller: BloggerAdminBundle:Page:index }
    requirements:
       _method:  GET

########### Work with posts #############
BloggerAdminBundle_edit_post:
    pattern:  /edit-post/{blog_id}
    defaults: { _controller: BloggerAdminBundle:Post:editPost }
    requirements:
      _method:  GET|POST
      blog_id: \d+

BloggerAdminBundle_submitEdition:
    pattern:  /edit-post/submit/{blog_id}
    defaults: { _controller: BloggerAdminBundle:Post:submitEdition }
    requirements:
      _method:  GET|POST
      blog_id: \d+

BloggerAdminBundle_create_new_post:
    pattern:  /create
    defaults: { _controller: BloggerAdminBundle:Post:addPost }
    requirements:
      _method: GET|POST

BloggerAdminBundle_save_new_post:
    pattern: /create/save
    defaults: { _controller: BloggerAdminBundle:Post:submitCreating }
    requirements:
      _method: GET|POST

BloggerAdminBundle_delete_post:
    pattern:  /deleting/{blogId}
    defaults: { _controller: BloggerAdminBundle:Post:delete }
    requirements:
      _method:  GET|POST
      blogId: \d+

################ Work with tags ##############
BloggerAdminBundle_edit_tags:
    pattern:  /managing-tags
    defaults: { _controller: BloggerAdminBundle:Tag:managingTags }
    requirements:
      _method: GET

BloggerAdminBundle_edit_concrete_tag:
    pattern:  /managing-tags/{tagId}
    defaults: { _controller: BloggerAdminBundle:Tag:editTag }
    requirements:
      _method:  GET|POST
      tagId: \d+

BloggerAdminBundle_submitTagEdition:
    pattern:  /managing-tags/submit/{tagId}
    defaults: { _controller: BloggerAdminBundle:Tag:submitEdition }
    requirements:
      _method:  GET|POST
      tagId: \d+

############# Administration error############
BloggerAdminBundle_get_rights_error:
    pattern:  /err
    defaults: { _controller: BloggerAdminBundle:Page:rightsError }
    requirements:
      _method: GET

############## Work with users ################
BloggerAdminBundle_edit_users_info:
    pattern:  /managing-users-info
    defaults: { _controller: BloggerAdminBundle:User:managingUsersInfo }
    requirements:
      _method: GET

BloggerAdminBundle_edit_info_of_concrete_user:
    pattern:  /managing-users-info/{userId}
    defaults: { _controller: BloggerAdminBundle:User:editUserInfo }
    requirements:
      _method: GET|POST
      userId: \d+

BloggerAdminBundle_submitUserInfoEdition:
    pattern:  /managing-users-info/submit/{userId}
    defaults: { _controller: BloggerAdminBundle:User:submitEdition }
    requirements:
      _method:  GET|POST
      userId: \d+