BloggerAdminBundle_homepage:
    pattern:  /
    defaults: { _controller: BloggerAdminBundle:Page:index }
    requirements:
       _method:  GET

########### Work with posts #############
BloggerAdminBundle_edit_post:
    pattern:  /edit-post/{blog_id}
    defaults: { _controller: BloggerAdminBundle:Post:editPost }
    requirements:
      _method:  GET|POST
      blog_id: \d+

BloggerAdminBundle_submitEdition:
    pattern:  /edit-post/submit/{blog_id}
    defaults: { _controller: BloggerAdminBundle:Post:submitEdition }
    requirements:
      _method:  GET|POST
      blog_id: \d+

BloggerAdminBundle_create_new_post:
    pattern:  /create
    defaults: { _controller: BloggerAdminBundle:Post:addPost }
    requirements:
      _method: GET|POST

BloggerAdminBundle_save_new_post:
    pattern: /create/save
    defaults: { _controller: BloggerAdminBundle:Post:submitCreating }
    requirements:
      _method: GET|POST

BloggerAdminBundle_delete_post:
    pattern:  /deleting/{blogId}
    defaults: { _controller: BloggerAdminBundle:Post:delete }
    requirements:
      _method:  GET|POST
      blogId: \d+

################ Work with tags ##############
BloggerAdminBundle_edit_tags:
    pattern:  /managing-tags
    defaults: { _controller: BloggerAdminBundle:Tag:managingTags }
    requirements:
      _method: GET

BloggerAdminBundle_edit_concrete_tag:
    pattern:  /managing-tags/{tagId}
    defaults: { _controller: BloggerAdminBundle:Tag:editTag }
    requirements:
      _method:  GET|POST
      tagId: \d+

BloggerAdminBundle_submitTagEdition:
    pattern:  /managing-tags/submit/{tagId}
    defaults: { _controller: BloggerAdminBundle:Tag:submitEdition }
    requirements:
      _method:  GET|POST
      tagId: \d+

############# Administration error############
BloggerAdminBundle_get_rights_error:
    pattern:  /err
    defaults: { _controller: BloggerAdminBundle:Page:rightsError }
    requirements:
      _method: GET

############## Work with users ################
BloggerAdminBundle_edit_users_info:
    pattern:  /managing-users-info
    defaults: { _controller: BloggerAdminBundle:User:managingUsersInfo }
    requirements:
      _method: GET

BloggerAdminBundle_edit_info_of_concrete_user:
    pattern:  /managing-users-info/{userId}
    defaults: { _controller: BloggerAdminBundle:User:editUserInfo }
    requirements:
      _method: GET|POST
      userId: \d+

BloggerAdminBundle_submitUserInfoEdition:
    pattern:  /managing-users-info/submit/{userId}
    defaults: { _controller: BloggerAdminBundle:User:submitEdition }
    requirements:
      _method:  GET|POST
      userId: \d+

BloggerAdminBundle_add_new_user:
    pattern:  /add-new-user
    defaults: { _controller: BloggerAdminBundle:User:addUser }
    requirements:
      _method: GET|POST

BloggerAdminBundle_submit_adding:
    pattern:  /add-new-user/saving
    defaults: { _controller: BloggerAdminBundle:User:submitAdding }
    requirements:
      _method: GET|POST

BloggerAdminBundle_delete_userInfo:
    pattern:  /managing-users-info/deleting/{userId}
    defaults: { _controller: BloggerAdminBundle:User:delete }
    requirements:
      _method:  GET|POST
      userId: \d+

################ Work with categories ##############
BloggerAdminBundle_edit_categories:
    pattern:  /managing-categories
    defaults: { _controller: BloggerAdminBundle:Category:managingCategories }
    requirements:
      _method: GET

BloggerAdminBundle_edit_concrete_category:
    pattern:  /managing-categories/{categoryId}
    defaults: { _controller: BloggerAdminBundle:Category:editCategory }
    requirements:
      _method:  GET|POST
      categoryId: \d+

BloggerAdminBundle_submitCategoryEdition:
    pattern:  /managing-categories/submit/{categoryId}
    defaults: { _controller: BloggerAdminBundle:Category:submitEdition }
    requirements:
      _method:  GET|POST
      categoryId: \d+

BloggerAdminBundle_delete_category:
    pattern:  /managing-categories/deleting/{categoryId}
    defaults: { _controller: BloggerAdminBundle:Category:delete }
    requirements:
      _method:  GET|POST
      categoryId: \d+

BloggerAdminBundle_add_new_category:
    pattern:  /add-new-category
    defaults: { _controller: BloggerAdminBundle:Category:addCategory }
    requirements:
      _method: GET|POST

BloggerAdminBundle_submit_adding_category:
    pattern:  /add-new-category/saving
    defaults: { _controller: BloggerAdminBundle:Category:submitAdding }
    requirements:
      _method: GET|POST