<?php

namespace Blogger\BlogBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    public function getAllCategories()
    {
        $qb = $this->createQueryBuilder('c')
            ->select('c')
            ->where('c.quantOfPosts != 0')
            ->orWhere('c.isDefault = 1')
            ->addOrderBy('c.catName', 'ASC');

        return $qb->getQuery()
            ->getResult();
    }

    public function getAllAndEvenEmptyCategories()
    {
        $qb = $this->createQueryBuilder('c')
            ->select('c')
            ->addOrderBy('c.catName', 'ASC');

        return $qb->getQuery()
            ->getResult();
    }

    public function findBySlug($slug) {
        $qb = $this->createQueryBuilder('c')
            ->select('c')
            ->where('c.slug = :slug')
            ->setParameter('slug', $slug);
        return $qb->getQuery()->getOneOrNullResult();
    }

    public function getQuantityOfPostsInAllCategories()
    {
        $categories = $this->getAllAndEvenEmptyCategories();

        foreach ($categories as $category) {
            $em = $this->getEntityManager();
            $category->setQuantOfPosts($em->getRepository('BloggerBlogBundle:Blog')->getQuantityOfPostsInCategory($category));
        }

    }
}
