<?php

namespace Blogger\BlogBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends EntityRepository
{
    public function getTagsWithPosts()
    {
        $qb = $this->createQueryBuilder('t')
            ->select('t', 'p')
            ->innerJoin('t.posts', 'p')
            ->addOrderBy('t.name', 'ASC');

        return $qb->getQuery()
            ->getResult();
    }

    public function getTags()
    {
        $qb = $this->createQueryBuilder('b')
            ->select('b')
            ->addOrderBy('b.name', 'ASC');

        return $qb->getQuery()
            ->getResult();
    }

    public function getTagWeights()
    {
        $tags = $this->getTagsWithPosts();
        if (empty($tags))
            return $tags;

        // Shuffle the tags
        shuffle($tags);
        $max = 0;
        $min = 10000000;

        foreach($tags as $tag) {
            $postCount = $tag->getPostCount();
            if($postCount < $min)
                $min = $postCount;
            if($postCount > $max)
                $max = $postCount;
        }

        foreach($tags as $tag) {
            $postCount = $tag->getPostCount();
            $maxFont = 24;
            $minFont = 12;
            $weight = ($postCount-$min+1) / ($max-$min+1) * ($maxFont - $minFont) + $minFont;
            $tag->setWeight($weight);
        }

        return $tags;

    }

    public function findBySlug($slug) {
        $qb = $this->createQueryBuilder('c')
            ->select('c')
            ->where('c.slug = :slug')
            ->setParameter('slug', $slug);

        return $qb->getQuery()->getOneOrNullResult();
    }
}
